using TreeSitter.Bindings;

namespace TreeSitter;

/// <summary>
/// Base for the failures the managed layer turns native return codes into.
/// </summary>
/// <remarks>
/// tree-sitter reports failure as <see langword="false"/>, <c>NULL</c>, or a null
/// node, never as anything self-describing. The point of these types is that the
/// context needed to diagnose the failure — an ABI version, a byte offset — is
/// captured at the one place that still has it.
/// </remarks>
public class TreeSitterException : Exception
{
    public TreeSitterException(string message)
        : base(message)
    {
    }

    public TreeSitterException(string message, Exception? innerException)
        : base(message, innerException)
    {
    }
}

/// <summary>
/// A grammar this runtime refuses: <c>ts_parser_set_language</c> returned
/// <see langword="false"/>.
/// </summary>
/// <remarks>
/// Always an ABI mismatch in practice — the grammar was generated by a
/// tree-sitter CLI outside the range <c>libtree-sitter</c> accepts. The version is
/// on the exception because the alternative is a refusal with no number in it,
/// which is unactionable: the fix is always to re-pin one side or the other in
/// <c>native/build.cs</c>, and that needs to know which side is which.
/// </remarks>
public sealed class IncompatibleLanguageException : TreeSitterException
{
    internal IncompatibleLanguageException(uint abiVersion)
        : base($"The tree-sitter runtime refused this grammar (language ABI version {abiVersion}). " +
               "The grammar and the runtime were built from incompatible versions; check the pins in native/build.cs.")
    {
        AbiVersion = abiVersion;
    }

    /// <summary>The value <c>ts_language_abi_version</c> reported for the refused grammar.</summary>
    public uint AbiVersion { get; }
}

/// <summary>
/// A query source tree-sitter would not compile.
/// </summary>
/// <remarks>
/// The byte offset is the whole value here. Query sources are multi-line
/// S-expressions and the error kinds are terse — <see cref="TSQueryError.NodeType"/>
/// on a rule the grammar does not have, <see cref="TSQueryError.Field"/> on a field
/// it does not define — so without a position the message names a mistake but not
/// which of thirty patterns made it. Offsets are byte offsets into the UTF-8
/// source, not character indices.
/// </remarks>
public sealed class QueryCompilationException : TreeSitterException
{
    internal QueryCompilationException(TSQueryError error, uint byteOffset, string detail)
        : base($"The query was rejected: {error} at byte {byteOffset}. {detail}")
    {
        Error = error;
        ByteOffset = byteOffset;
    }

    /// <summary>Why the pattern was rejected.</summary>
    public TSQueryError Error { get; }

    /// <summary>Byte offset into the query source where the problem starts.</summary>
    public uint ByteOffset { get; }
}

/// <summary>
/// A query whose patterns carry predicates, compiled under
/// <see cref="PredicateHandling.Reject"/>.
/// </summary>
/// <remarks>
/// Not a tree-sitter error, and no longer a statement that predicates do not work —
/// they do. This is the opt-in strictness a caller asks for when a query source is
/// supposed to stay structural, so that a predicate appearing in one is a change
/// somebody has to notice rather than a change in what the query means.
/// </remarks>
public sealed class PredicateRefusedException : TreeSitterException
{
    internal PredicateRefusedException(uint patternIndex, string[] predicateNames)
        : base($"Pattern {patternIndex} uses predicates ({string.Join(", ", predicateNames)}) and this query was " +
               "compiled with PredicateHandling.Reject. Rewrite the pattern without them, or compile with " +
               "PredicateHandling.Evaluate.")
    {
        PatternIndex = patternIndex;
        PredicateNames = predicateNames;
    }

    /// <summary>Which pattern carried them, in <c>ts_query_pattern_count</c>'s index space.</summary>
    public uint PatternIndex { get; }

    /// <summary>The predicates found, as written: <c>#eq?</c>, <c>#match?</c>.</summary>
    public IReadOnlyList<string> PredicateNames { get; }
}

/// <summary>
/// A predicate this host will not run: an unknown name, the wrong arity or argument
/// types, or a regular expression outside the dialect <c>#match?</c> accepts.
/// </summary>
/// <remarks>
/// <para>
/// Thrown while the query is being compiled, which is the whole point. tree-sitter
/// parses <c>#is-not?</c> as happily as <c>#eq?</c> and hands both back unevaluated;
/// a host that skipped the one it did not recognize would produce a pattern matching
/// strictly more than it reads, with nothing anywhere reporting a problem. So an
/// unrecognized predicate is a query bug and is reported like one, with the pattern
/// it came from quoted.
/// </para>
/// <para>
/// The regex cases are the same argument at one remove. Predicates in the wild are
/// written against Rust's <c>regex</c> crate, and where .NET would quietly read a
/// pattern as something else — a POSIX bracket expression — the query is refused
/// instead.
/// </para>
/// </remarks>
public sealed class QueryPredicateException : TreeSitterException
{
    internal QueryPredicateException(
        uint patternIndex,
        string predicateName,
        string detail,
        Func<uint, string> describePattern,
        Exception? innerException = null)
        : base($"Pattern {patternIndex} writes #{predicateName}, and {detail} {describePattern(patternIndex)}",
               innerException)
    {
        PatternIndex = patternIndex;
        PredicateName = "#" + predicateName;
    }

    /// <summary>Which pattern wrote it, in <c>ts_query_pattern_count</c>'s index space.</summary>
    public uint PatternIndex { get; }

    /// <summary>The predicate, as written: <c>#is-not?</c>.</summary>
    public string PredicateName { get; }
}
